version: '3.8'

services:

  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: test
    volumes:
      - postgres_volume:/var/lib/postgresql/data
    ports:
    - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d test"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: unless-stopped

volumes:
  postgres_volume: