# Generated by Django 4.2 on 2023-12-30 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BankAccount',
            new_name='Account',
        ),
    ]
